name: tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install package + test deps
        run: pip install -e ".[test]"

      - name: Run tests
        env:
          # Repo Settings -> Secrets and variables -> Actions
          # Skips api tests if not available (basically everything)
          DONUTSMP_API_TOKEN: ${{ secrets.DONUTSMP_API_TOKEN }}
        run: python -m pytest -v
